// Code generated by MockGen. DO NOT EDIT.
// Source: logservice/logpuller/debug.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	logpuller "github.com/pingcap/ticdc/logservice/logpuller"
)

// MockDebugInfoProvider is a mock of DebugInfoProvider interface.
type MockDebugInfoProvider struct {
	ctrl     *gomock.Controller
	recorder *MockDebugInfoProviderMockRecorder
}

// MockDebugInfoProviderMockRecorder is the mock recorder for MockDebugInfoProvider.
type MockDebugInfoProviderMockRecorder struct {
	mock *MockDebugInfoProvider
}

// NewMockDebugInfoProvider creates a new mock instance.
func NewMockDebugInfoProvider(ctrl *gomock.Controller) *MockDebugInfoProvider {
	mock := &MockDebugInfoProvider{ctrl: ctrl}
	mock.recorder = &MockDebugInfoProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDebugInfoProvider) EXPECT() *MockDebugInfoProviderMockRecorder {
	return m.recorder
}

// GetPullerDebugInfo mocks base method.
func (m *MockDebugInfoProvider) GetPullerDebugInfo(options logpuller.PullerDebugOptions) logpuller.PullerDebugInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullerDebugInfo", options)
	ret0, _ := ret[0].(logpuller.PullerDebugInfo)
	return ret0
}

// GetPullerDebugInfo indicates an expected call of GetPullerDebugInfo.
func (mr *MockDebugInfoProviderMockRecorder) GetPullerDebugInfo(options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullerDebugInfo", reflect.TypeOf((*MockDebugInfoProvider)(nil).GetPullerDebugInfo), options)
}

// GetPullerDebugRegion mocks base method.
func (m *MockDebugInfoProvider) GetPullerDebugRegion(subID logpuller.SubscriptionID, regionID uint64) (logpuller.PullerRegionDebugDetail, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullerDebugRegion", subID, regionID)
	ret0, _ := ret[0].(logpuller.PullerRegionDebugDetail)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetPullerDebugRegion indicates an expected call of GetPullerDebugRegion.
func (mr *MockDebugInfoProviderMockRecorder) GetPullerDebugRegion(subID, regionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullerDebugRegion", reflect.TypeOf((*MockDebugInfoProvider)(nil).GetPullerDebugRegion), subID, regionID)
}
