// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pingcap/ticdc/pkg/messaging (interfaces: MessageCenter)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	messaging "github.com/pingcap/ticdc/pkg/messaging"
	node "github.com/pingcap/ticdc/pkg/node"
)

// MockMessageCenter is a mock of MessageCenter interface.
type MockMessageCenter struct {
	ctrl     *gomock.Controller
	recorder *MockMessageCenterMockRecorder
}

// MockMessageCenterMockRecorder is the mock recorder for MockMessageCenter.
type MockMessageCenterMockRecorder struct {
	mock *MockMessageCenter
}

// NewMockMessageCenter creates a new mock instance.
func NewMockMessageCenter(ctrl *gomock.Controller) *MockMessageCenter {
	mock := &MockMessageCenter{ctrl: ctrl}
	mock.recorder = &MockMessageCenterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageCenter) EXPECT() *MockMessageCenterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockMessageCenter) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockMessageCenterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMessageCenter)(nil).Close))
}

// DeRegisterHandler mocks base method.
func (m *MockMessageCenter) DeRegisterHandler(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeRegisterHandler", arg0)
}

// DeRegisterHandler indicates an expected call of DeRegisterHandler.
func (mr *MockMessageCenterMockRecorder) DeRegisterHandler(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeRegisterHandler", reflect.TypeOf((*MockMessageCenter)(nil).DeRegisterHandler), arg0)
}

// IsReadyToSend mocks base method.
func (m *MockMessageCenter) IsReadyToSend(arg0 node.ID) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsReadyToSend", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsReadyToSend indicates an expected call of IsReadyToSend.
func (mr *MockMessageCenterMockRecorder) IsReadyToSend(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReadyToSend", reflect.TypeOf((*MockMessageCenter)(nil).IsReadyToSend), arg0)
}

// OnNodeChanges mocks base method.
func (m *MockMessageCenter) OnNodeChanges(arg0 map[node.ID]*node.Info) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnNodeChanges", arg0)
}

// OnNodeChanges indicates an expected call of OnNodeChanges.
func (mr *MockMessageCenterMockRecorder) OnNodeChanges(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnNodeChanges", reflect.TypeOf((*MockMessageCenter)(nil).OnNodeChanges), arg0)
}

// RegisterHandler mocks base method.
func (m *MockMessageCenter) RegisterHandler(arg0 string, arg1 messaging.MessageHandler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterHandler", arg0, arg1)
}

// RegisterHandler indicates an expected call of RegisterHandler.
func (mr *MockMessageCenterMockRecorder) RegisterHandler(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterHandler", reflect.TypeOf((*MockMessageCenter)(nil).RegisterHandler), arg0, arg1)
}

// SendCommand mocks base method.
func (m *MockMessageCenter) SendCommand(arg0 *messaging.TargetMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCommand", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCommand indicates an expected call of SendCommand.
func (mr *MockMessageCenterMockRecorder) SendCommand(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCommand", reflect.TypeOf((*MockMessageCenter)(nil).SendCommand), arg0)
}

// SendEvent mocks base method.
func (m *MockMessageCenter) SendEvent(arg0 *messaging.TargetMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEvent", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEvent indicates an expected call of SendEvent.
func (mr *MockMessageCenterMockRecorder) SendEvent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEvent", reflect.TypeOf((*MockMessageCenter)(nil).SendEvent), arg0)
}
